### ISSUE TITLE
App link is broken

### ISSUE THREAD

**Issue by rajbos** [SvanBoxel/organization-workflows#23]
Hi,

I wanted to test your action but cannot install the app :-(. 
The link points to [https://github.com/apps/organization-workflows-production](https://github.com/apps/organization-workflows-production) which returns a 404. Searching on the marketplace also doesn't show an available app.

**Comment by SvanBoxel** [comment]
Whoops, good catch! The correct link is https://github.com/apps/organization-workflows. I'll update the readme.

**Comment by joshjohanning** [comment]
What's needed to get it updated here too? https://probot.github.io/apps/organization-workflows/ 

@SvanBoxel

**Comment by SvanBoxel** [comment]
@joshjohanning The probot website is open source. To suggest a change in that file you can open a pr here: https://github.com/probot/probot.github.io/blob/master/_apps/organization-workflows.md
