### ISSUE TITLE
Error: Unable to resolve actions. Repository not found : svanboxel/organization-workflow.

### ISSUE THREAD

**Issue by joshjohanning** [SvanBoxel/organization-workflows#38]
What am I missing? :) 

> Error: Unable to resolve actions. Repository not found : svanboxel/organization-workflow.

![image](https://user-images.githubusercontent.com/19912012/148973833-6950e798-c803-44c1-9417-662d7c699707.png)

**Comment by SvanBoxel** [comment]
It's `svanboxel/organization-workflows`, not `svanboxel/organization-workflow`. You miss the `s`.

**Comment by joshjohanning** [comment]
🙈
