### ISSUE TITLE
Feature Request - Get Issue number

### ISSUE THREAD

**Issue by leeseojune53** [SvanBoxel/organization-workflows#49]
I want get Issue number, but, currently your app doesn't have get Issue number proerty.
So, I think add Issue number in data field.
![스크린샷 2022-09-04 오후 11 35 02](https://user-images.githubusercontent.com/61784568/188318930-625663d9-3025-4203-a83f-f98a8e748436.png)

**Comment by leeseojune53** [comment]
I already tried probot property :( 

![스크린샷 2022-09-05 오전 12 13 17](https://user-images.githubusercontent.com/61784568/188320618-48ee6fb3-9e6e-4ffc-b6f5-1a689fcae803.png)

**Comment by leeseojune53** [comment]
REPO_NAME can get repository name, but issue or pr number can't get that number

**Comment by leeseojune53** [comment]
@SvanBoxel 
can you advice to me?

**Comment by SvanBoxel** [comment]
The app is triggered on push events, which don't have a reference to a issue/PR number. You could however leverage GitHub's API to get commit associated PRs: https://github.com/orgs/community/discussions/24679

Hope this helps. ✌🏽
